### ISSUE TITLE
Allow/Ignore List for Keys

### ISSUE THREAD

**Issue by sheeley** [aerobounce/defaults.sh#2]
I'm a big fan of defaults.sh! I converted a number of my plists in git into shell scripts over last weekend. 

One of my goals, though, was to stop seeing changes that I don't care about. I was encountering issues where Sparkle, for example, would update a plist value that I don't actually care about.

If I wanted to filter out a single Sparkle entry, I could do something like this, and not have to worry about it
```
ds com.some.app | grep -v SULastCheckTime
```

This doesn't necessarily scale well, IMO, and for values that are multi-line, I wouldn't expect it to work at all.

I'm curious whether you'd be open to adding arguments so it would be possible to run
```
ds com.some.app --ignore 'SU*' --ignore SomeKeyIDoNotCareAbout --allow SUThisIActuallyCareAbout
```
In my mind, allow would override ignore, and either would accept multiple values. I'd be happy to send a PR if you're interested.

**Comment by aerobounce** [comment]
First, thanks for letting me know that there is a person like me who loves to script defaults using `ds`. That means a lot to me really 🤝.
Second, yes, that is the exactly the problem I was feeling annoying too, yet, somehow I haven't implemented yet to solve the problem.

I'm interested in your PR, please feel free to open. I'd need to test and review the whole code so it might take some time to merge though, it'd definitely worth I believe.
That wildcard filtering sounds awesome.

**Comment by sheeley** [comment]
I'll move discussion to #3
