### ISSUE TITLE
How to use currentHost?

### ISSUE THREAD

**Issue by sheeley** [aerobounce/defaults.sh#4]
When I use `ds save`, I see `NSGlobalDomain.currentHost.sh`, including modifier keys like:
```
defaults -currentHost write NSGlobalDomain "com.apple.keyboard.modifiermapping.1118-1957-0" '
<array>
	<dict>
		<key>HIDKeyboardModifierMappingDst</key>
		<real>30064771299</real>
		<key>HIDKeyboardModifierMappingSrc</key>
		<real>30064771302</real>
	</dict>
	<dict>
		<key>HIDKeyboardModifierMappingDst</key>
		<integer>30064771303</integer>
		<key>HIDKeyboardModifierMappingSrc</key>
		<integer>30064771298</integer>
	</dict>
	<dict>
		<key>HIDKeyboardModifierMappingDst</key>
		<real>30064771298</real>
		<key>HIDKeyboardModifierMappingSrc</key>
		<real>30064771303</real>
	</dict>
	<dict>
		<key>HIDKeyboardModifierMappingDst</key>
		<integer>30064771302</integer>
		<key>HIDKeyboardModifierMappingSrc</key>
		<real>30064771299</real>
	</dict>
</array>
'
```
Is there a way to access this directly? 
`ds -d NSGlobalDomain` doesn't include these, and `ds` doesn't have a `-currentHost` flag. Anything I'm missing?

**Comment by aerobounce** [comment]
Good point.
Currently there's no support for that, I'll look into if I can add it as new option.

**Comment by sheeley** [comment]
Happy to contribute here, too. Would a `-currentHost` flag that gets passed through make the most sense?

**Comment by aerobounce** [comment]
Thanks for that 👍
However I've managed to implement `currentHost` command now, could you try the new version?

**Comment by sheeley** [comment]
Yes, this is great!
